# use ahash instead
disallowed-types = [
    { path = "std::collections::HashMap", reason = "use ahash::AHashMap instead"},
    { path = "std::collections::HashSet", reason = "use ahash::AHashSet instead"},
]
