apiVersion: 1

datasources:
  - name: TimescaleDB
    type: grafana-postgresql-datasource
    access: proxy
    isDefault: true
    editable: true
    url: db:5432
    user: postgres
    database: tado
    jsonData:
      sslmode: disable
      postgresVersion: 1300
      timescaledb: true
    secureJsonData:
      password: postgres
