apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    access: proxy
    isDefault: true
    editable: false
    url: db:5432
    user: postgres
    database: tado
    jsonData:
      sslmode: disable
      postgresVersion: 1300
      timescaledb: true
    secureJsonData:
      password: postgres
